### ISSUE TITLE
Panic when configuration is not present

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#107]
For the following config:

```
cloudquery {
	plugin_directory = "."
  
	provider "gcp" {
	  source  = "cloudquery/cq-provider-gcp"
	  version = "latest"
	}
  
	connection {
	  dsn = "host=localhost user=postgres password=pass DB.name=postgres port=5432"
	}
}

provider "gcp" {
	configuration {
	}
	resources = []
}
```

panic is printed:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1666328]
goroutine 118 [running]:
github.com/cloudquery/cloudquery/pkg/config/convert.Body(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/ep/go/pkg/mod/github.com/cloudquery/cloudquery@v0.13.3/pkg/config/convert/converter.go:65 +0x228
github.com/cloudquery/cloudquery/pkg/client.(*Client).Fetch.func1(0x0, 0x0)
        /Users/ep/go/pkg/mod/github.com/cloudquery/cloudquery@v0.13.3/pkg/client/client.go:188 +0xa5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000020780, 0xc0001d6b40)
        /Users/ep/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/ep/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
exit status 2
```

**Comment by roneli** [comment]
Fixed in #113
