### ISSUE TITLE
Error when syncing/backing up cloudflare to file

### ISSUE THREAD

**Issue by shoepping** [cloudquery/cloudquery#12334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

syncing cloudflare to local file leads to an Segementation violation
tried on different linux distributions
API Token has all rights to all zones and configs
```
 INF finished call grpc.code=OK grpc.component=server grpc.method=Sync grpc.method_type=server_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:03+02:00 grpc.time_ms=35941.48 module=cli peer.address=@ protocol=grpc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x109f0e1]

goroutine 69 [running]:
github.com/cloudquery/plugin-sdk/v4/writers/streamingbatchwriter.(*streamingWorkerManager[...]).run(0xc0005c7c40, {0x161a008, 0xc0000b4340}, 0xc0005920f8, {0xc0005dac00?, 0x17})
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.8.1-rc1/writers/streamingbatchwriter/streamingbatchwriter.go:346 +0x221
created by github.com/cloudquery/plugin-sdk/v4/writers/streamingbatchwriter.(*StreamingBatchWriter).startWorker
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.8.1-rc1/writers/streamingbatchwriter/streamingbatchwriter.go:254 +0x905
2023-07-18T13:10:39Z INF End sync destinations=["file (v3.3.0)"] module=cli source="cloudflare (v5.0.0)" sync_time=2023-07-18T13:10:00Z
```

### Expected Behavior

no segmentation violation

### CloudQuery (redacted) config

```
kind: source
# Common source-plugin configuration
spec:
  name: cloudflare
  path: cloudquery/cloudflare
  version: "v5.0.0"
  concurrency: 1000
  tables: ["*"]
  destinations: ["file"]
  # Cloudflare specific configuration
  spec:
    api_token: ""
    api_key: ""
    api_email: ""
```

```
kind: destination
spec:
  name: "file"
  path: "cloudquery/file"
  version: "v3.3.0"
  spec:
    path: "path/to/files/{{TABLE}}/{{UUID}}.{{FORMAT}}"
#    batch_size: 10000 # optional
#    batch_size_bytes: 52428800 # optional
#    batch_timeout: 30s # optional
    format: "csv" # options: parquet, json, csv
    format_spec:
      delimiter: ","


```

### Steps To Reproduce

try to sync cloudflare to local file
$./cloudquery sync cloudflare.yaml file.yaml --log-console

### CloudQuery (redacted) logs

```
2023-07-18T13:09:53Z INF Loading spec(s) args=["cloudflare.yaml","file.yaml"] module=cli
2023-07-18T13:09:56Z INF Plugin server listening address=/tmp/cq-yCjgLeguuEPLwJqL.sock module=cli
2023-07-18T13:09:59Z INF Plugin server listening address=/tmp/cq-MQEaznlVVeKYfHFi.sock module=cli
2023-07-18T13:10:00Z INF started call grpc.code=OK grpc.component=server grpc.method=GetVersions grpc.method_type=unary grpc.service=cloudquery.discovery.v1.Discovery grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.057 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z INF finished call grpc.code=OK grpc.component=server grpc.method=GetVersions grpc.method_type=unary grpc.service=cloudquery.discovery.v1.Discovery grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.1 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z WRN the top-level `concurrency` option is deprecated. Please use the plugin-level concurrency option instead field=concurrency module=cli source=cloudflare
2023-07-18T13:10:00Z INF started call grpc.code=OK grpc.component=server grpc.method=GetVersions grpc.method_type=unary grpc.service=cloudquery.discovery.v1.Discovery grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.089 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z INF finished call grpc.code=OK grpc.component=server grpc.method=GetVersions grpc.method_type=unary grpc.service=cloudquery.discovery.v1.Discovery grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.125 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z INF Start sync destinations=["file (v3.3.0)"] module=cli source="cloudflare (v5.0.0)" sync_time=2023-07-18T13:10:00Z
2023-07-18T13:10:00Z INF started call grpc.code=OK grpc.component=server grpc.method=Init grpc.method_type=unary grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.043 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z INF finished call grpc.code=OK grpc.component=server grpc.method=Init grpc.method_type=unary grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.55 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:00Z INF started call grpc.code=OK grpc.component=server grpc.method=Init grpc.method_type=unary grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=0.027 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:03Z INF finished call grpc.code=OK grpc.component=server grpc.method=Init grpc.method_type=unary grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:00+02:00 grpc.time_ms=3207.835 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:03Z INF Start fetching resources destinations=["file (v3.3.0)"] module=cli source="cloudflare (v5.0.0)"
2023-07-18T13:10:03Z INF started call grpc.code=OK grpc.component=server grpc.method=Sync grpc.method_type=server_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:03+02:00 grpc.time_ms=0.145 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:03Z INF started call grpc.code=OK grpc.component=server grpc.method=Write grpc.method_type=client_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:03+02:00 grpc.time_ms=2.977 module=cli peer.address=@ protocol=grpc
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_dns_records
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_access_groups
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_access_groups
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_certificate_packs
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_access_groups
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_dns_records
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_certificate_packs
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_certificate_packs
2023-07-18T13:10:03Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_dns_records
2023-07-18T13:10:03Z INF top level table resolver started client= module=cloudflare-src table=cloudflare_accounts
2023-07-18T13:10:05Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=2 table=cloudflare_certificate_packs
2023-07-18T13:10:05Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84 module=cloudflare-src table=cloudflare_images
2023-07-18T13:10:05Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=2 table=cloudflare_certificate_packs
2023-07-18T13:10:05Z INF top level table resolver started client= module=cloudflare-src table=cloudflare_ips
2023-07-18T13:10:05Z INF table sync finished client= errors=0 module=cloudflare-src resources=135 table=cloudflare_ips
2023-07-18T13:10:05Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_waf_packages
2023-07-18T13:10:06Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=20 table=cloudflare_certificate_packs
2023-07-18T13:10:06Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_waf_packages
2023-07-18T13:10:06Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_packages
2023-07-18T13:10:06Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_groups
2023-07-18T13:10:06Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_rules
2023-07-18T13:10:06Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_waf_packages
2023-07-18T13:10:07Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_packages
2023-07-18T13:10:07Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_groups
2023-07-18T13:10:07Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_rules
2023-07-18T13:10:07Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_waf_overrides
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=89 table=cloudflare_dns_records
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_waf_overrides
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=3 table=cloudflare_dns_records
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_waf_overrides
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=1 table=cloudflare_access_groups
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84 module=cloudflare-src table=cloudflare_worker_meta_data
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=1 table=cloudflare_access_groups
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e module=cloudflare-src table=cloudflare_worker_routes
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=27 table=cloudflare_dns_records
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 module=cloudflare-src table=cloudflare_worker_routes
2023-07-18T13:10:08Z INF table sync finished client= errors=0 module=cloudflare-src resources=1 table=cloudflare_accounts
2023-07-18T13:10:08Z INF table sync finished client= errors=0 module=cloudflare-src resources=11 table=cloudflare_account_members
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 module=cloudflare-src table=cloudflare_worker_routes
2023-07-18T13:10:08Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84 errors=0 module=cloudflare-src resources=0 table=cloudflare_images
2023-07-18T13:10:08Z INF top level table resolver started client=650233be2c7cbbbd067521ccd5133d84 module=cloudflare-src table=cloudflare_zones
2023-07-18T13:10:09Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=1 table=cloudflare_access_groups
2023-07-18T13:10:09Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_overrides
2023-07-18T13:10:09Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_overrides
2023-07-18T13:10:09Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=0 table=cloudflare_waf_overrides
2023-07-18T13:10:10Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:4590e47bed1827ac8196b75b699e576e errors=0 module=cloudflare-src resources=0 table=cloudflare_worker_routes
2023-07-18T13:10:10Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:e2a21234ba4c33b043ffaa408ed3d543 errors=0 module=cloudflare-src resources=0 table=cloudflare_worker_routes
2023-07-18T13:10:10Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=28 table=cloudflare_worker_routes
2023-07-18T13:10:11Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84 errors=0 module=cloudflare-src resources=3 table=cloudflare_zones
2023-07-18T13:10:19Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84 errors=0 module=cloudflare-src resources=10 table=cloudflare_worker_meta_data
2023-07-18T13:10:19Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84 errors=0 module=cloudflare-src resources=0 table=cloudflare_worker_cron_triggers
2023-07-18T13:10:19Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84 errors=0 module=cloudflare-src resources=0 table=cloudflare_workers_secrets
2023-07-18T13:10:39Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=3 table=cloudflare_waf_packages
2023-07-18T13:10:39Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=30 table=cloudflare_waf_groups
2023-07-18T13:10:39Z INF table sync finished client=650233be2c7cbbbd067521ccd5133d84:6102f1b908d043d7b16b6da52e5ad459 errors=0 module=cloudflare-src resources=3023 table=cloudflare_waf_rules
2023-07-18T13:10:39Z INF finished call grpc.code=OK grpc.component=server grpc.method=Sync grpc.method_type=server_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-07-18T15:10:03+02:00 grpc.time_ms=35941.48 module=cli peer.address=@ protocol=grpc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x109f0e1]

goroutine 69 [running]:
github.com/cloudquery/plugin-sdk/v4/writers/streamingbatchwriter.(*streamingWorkerManager[...]).run(0xc0005c7c40, {0x161a008, 0xc0000b4340}, 0xc0005920f8, {0xc0005dac00?, 0x17})
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.8.1-rc1/writers/streamingbatchwriter/streamingbatchwriter.go:346 +0x221
created by github.com/cloudquery/plugin-sdk/v4/writers/streamingbatchwriter.(*StreamingBatchWriter).startWorker
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.8.1-rc1/writers/streamingbatchwriter/streamingbatchwriter.go:254 +0x905
2023-07-18T13:10:39Z INF End sync destinations=["file (v3.3.0)"] module=cli source="cloudflare (v5.0.0)" sync_time=2023-07-18T13:10:00Z
2023-07-18T13:10:39Z INF Sending sync summary to analyticsv1.cloudquery.io:443 module=cli
2023-07-18T13:10:39Z INF waiting for source plugin to terminate module=cli
2023-07-18T13:10:39Z INF waiting for source plugin to terminate module=cli
2023-07-18T13:10:39Z INF Got stop signal. Plugin server shutting down address=/tmp/cq-yCjgLeguuEPLwJqL.sock module=cli signal=interrupt
Error: failed to sync v3 source cloudflare: rpc error: code = Unavailable desc = error reading from server: EOF
2023-07-18T13:10:39Z ERR exiting with error error="failed to sync v3 source cloudflare: rpc error: code = Unavailable desc = error reading from server: EOF" module=cli
```

### CloudQuery version

3.9.2

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Going to close this per @disq comment. Please comment if the issue persists and I'll re-open

**Comment by shoepping** [comment]
thx. the error is gone, however the sync does not finish and runs forever, however in the logs i see that table sync finished for everything. i will open a new issue for that
