### ISSUE TITLE
bug: type mismatch: got=utf8, want=date64

### ISSUE THREAD

**Issue by nicosuave** [cloudquery/cloudquery#12524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems the `date` datatype in Postgres is unhandled when copying data. Timestamp type seems to move over fine FWIW. 

I now see (what I assume to be staging tables based on the uuid suffix) sibling tables in the destination as well, as I saw a panic prior to any rows being copied if helpful

### Expected Behavior

For `date` datatype to be handled

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: abc
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v2.0.3"
  destinations: ["xyz"]
  tables: ["*"]
  spec:
    connection_string: ...
---
kind: destination
spec:
  name: xyz
  path: cloudquery/duckdb
  version: "v4.1.2"
  write_mode: overwrite
  spec:
    connection_string: ...
```

### Steps To Reproduce

Create a table with a `date` datatype and try to sync that

### CloudQuery (redacted) logs

```
/ Syncing resources... (34/-, 337 resources/s) [0s] 
                                                    

- Syncing resources... (34/-, 169 resources/s) [0s] 
                                                    

\ Syncing resources... (34/-, 113 resources/s) [0s] 
                                                    

| Syncing resources... (34/-, 85 resources/s) [0s] 
                                                    

/ Syncing resources... (34/-, 68 resources/s) [0s] 
                                                    

- Syncing resources... (34/-, 68 resources/s) [0s] 
                                                    

\ Syncing resources... (34/-, 68 resources/s) [0s] 
                                                    

| Syncing resources... (34/-, 68 resources/s) [0s] 
                                                    

/ Syncing resources... (34/-, 68 resources/s) [0s] 
                                                    

- Syncing resources... (34/-, 68 resources/s) [1s] 
                                                    

\ Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

| Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

/ Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

- Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

\ Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

| Syncing resources... (34/-, 34 resources/s) [1s] 
                                                    

/ Syncing resources... (34/-, 23 resources/s) [1s] 
                                                    

- Syncing resources... (34/-, 23 resources/s) [1s] 
                                                    

\ Syncing resources... (34/-, 23 resources/s) [1s] 
                                                    

| Syncing resources... (34/-, 23 resources/s) [2s] 
                                                    

/ Syncing resources... (34/-, 23 resources/s) [2s] 
                                                    

- Syncing resources... (34/-, 23 resources/s) [2s] 
                                                    

\ Syncing resources... (34/-, 17 resources/s) [2s] 
                                                    

| Syncing resources... (34/-, 17 resources/s) [2s] 
                                                    

/ Syncing resources... (34/-, 17 resources/s) [2s] 
                                                    

- Syncing resources... (34/-, 17 resources/s) [2s] 
                                                    

\ Syncing resources... (34/-, 17 resources/s) [2s] 
                                                    

| Syncing resources... (34/-, 14 resources/s) [2s] 
                                                    

/ Syncing resources... (34/-, 14 resources/s) [2s] 
                                                    

- Syncing resources... (34/-, 14 resources/s) [3s] 
                                                    

\ Syncing resources... (34/-, 14 resources/s) [3s] 
                                                    

| Syncing resources... (34/-, 14 resources/s) [3s] 
                                                    

/ Syncing resources... (34/-, 14 resources/s) [3s] 
                                                    

- Syncing resources... (34/-, 11 resources/s) [3s] 
                                                    

\ Syncing resources... (34/-, 11 resources/s) [3s] 
                                                    

| Syncing resources... (34/-, 11 resources/s) [3s] 
                                                    

/ Syncing resources... (34/-, 11 resources/s) [3s] 
                                                    

- Syncing resources... (34/-, 11 resources/s) [3s] 
                                                    

\ Syncing resources... (34/-, 10 resources/s) [3s] 
                                                    

| Syncing resources... (34/-, 10 resources/s) [4s] 
                                                    

/ Syncing resources... (34/-, 10 resources/s) [4s] 
                                                    

- Syncing resources... (34/-, 10 resources/s) [4s] 
                                                    

\ Syncing resources... (34/-, 10 resources/s) [4s] 
                                                    

| Syncing resources... (34/-, 10 resources/s) [4s] 
                                                    

/ Syncing resources... (34/-, 8 resources/s) [4s] 
                                                    

- Syncing resources... (34/-, 8 resources/s) [4s] 
                                                    

\ Syncing resources... (34/-, 8 resources/s) [4s] 
                                                    

| Syncing resources... (34/-, 8 resources/s) [4s] 
                                                    

/ Syncing resources... (34/-, 8 resources/s) [4s] 
                                                    

- Syncing resources... (34/-, 8 resources/s) [5s] 
                                                    

\ Syncing resources... (189/-, 8 resources/s) [5s] 
                                                    

| Syncing resources... (411/-, 8 resources/s) [5s] 
                                                    

/ Syncing resources... (624/-, 8 resources/s) [5s] 
                                                    

- Syncing resources... (862/-, 8 resources/s) [5s] 
                                                    

\ Syncing resources... (1076/-, 212 resources/s) [5s] 
                                                      

| Syncing resources... (1082/-, 212 resources/s) [5s] 
                                                      

/ Syncing resources... (1082/-, 212 resources/s) [5s] 
                                                      

- Syncing resources... (1082/-, 212 resources/s) [5s] 
                                                      

\ Syncing resources... (1082/-, 212 resources/s) [5s] 
                                                      

| Syncing resources... (1148/-, 212 resources/s) [6s] 
                                                      

/ Syncing resources... (1371/-, 255 resources/s) [6s] 
                                                      

- Syncing resources... (1621/-, 255 resources/s) [6s] 
                                                      

\ Syncing resources... (1773/-, 255 resources/s) [6s] 
                                                      

| Syncing resources... (1965/-, 255 resources/s) [6s] 
                                                      

/ Syncing resources... (2083/-, 255 resources/s) [6s] 
                                                      

- Syncing resources... (2083/-, 255 resources/s) [6s] 
                                                      

\ Syncing resources... (2083/-, 375 resources/s) [6s] 
                                                      

| Syncing resources... (2083/-, 375 resources/s) [6s] 
                                                      

/ Syncing resources... (2083/-, 375 resources/s) [6s] 
                                                      

- Syncing resources... (2189/-, 375 resources/s) [7s] 
                                                      

\ Syncing resources... (2388/-, 375 resources/s) [7s] 
                                                      

| Syncing resources... (2598/-, 477 resources/s) [7s] 
                                                      

/ Syncing resources... (2788/-, 477 resources/s) [7s] 
                                                      

- Syncing resources... (3065/-, 477 resources/s) [7s] 
                                                      

\ Syncing resources... (3084/-, 477 resources/s) [7s] 
                                                      

| Syncing resources... (3084/-, 477 resources/s) [7s] 
                                                      

/ Syncing resources... (3084/-, 477 resources/s) [7s] 
                                                      

- Syncing resources... (3084/-, 559 resources/s) [7s] 
                                                      

\ Syncing resources... (3169/-, 559 resources/s) [7s] 
                                                      

| Syncing resources... (3392/-, 559 resources/s) [8s] 
                                                      

/ Syncing resources... (3591/-, 559 resources/s) [8s] 
                                                      

- Syncing resources... (3846/-, 559 resources/s) [8s] 
                                                      

\ Syncing resources... (4071/-, 751 resources/s) [8s] 
                                                      

| Syncing resources... (4080/-, 751 resources/s) [8s] 
                                                      

/ Syncing resources... (4080/-, 751 resources/s) [8s] 
                                                      

- Syncing resources... (4080/-, 751 resources/s) [8s] 
                                                      

\ Syncing resources... (4080/-, 751 resources/s) [8s] 
                                                      

| Syncing resources... (4097/-, 751 resources/s) [8s] 
                                                      

/ Syncing resources... (4304/-, 791 resources/s) [8s] 
                                                      

- Syncing resources... (4576/-, 791 resources/s) [9s] 
                                                      

\ Syncing resources... (4792/-, 791 resources/s) [9s] 
                                                      

| Syncing resources... (5006/-, 791 resources/s) [9s] 
                                                      

/ Syncing resources... (5081/-, 791 resources/s) [9s] 
                                                      

- Syncing resources... (5081/-, 946 resources/s) [9s] 
                                                      

\ Syncing resources... (5081/-, 946 resources/s) [9s] 
                                                      

| Syncing resources... (5081/-, 946 resources/s) [9s] 
                                                      

/ Syncing resources... (5114/-, 946 resources/s) [9s] 
                                                      

- Syncing resources... (5376/-, 946 resources/s) [9s] 
                                                      

\ Syncing resources... (5579/-, 946 resources/s) [9s] 
                                                      

| Syncing resources... (5816/-, 1068 resources/s) [10s] 
                                                        

/ Syncing resources... (6012/-, 1068 resources/s) [10s] 
                                                        

- Syncing resources... (6082/-, 1068 resources/s) [10s] 
                                                        

\ Syncing resources... (6082/-, 1068 resources/s) [10s] 
                                                        

| Syncing resources... (6082/-, 1068 resources/s) [10s] 
                                                        

/ Syncing resources... (6082/-, 1122 resources/s) [10s] 
                                                        

- Syncing resources... (6127/-, 1122 resources/s) [10s] 
                                                        

\ Syncing resources... (6386/-, 1122 resources/s) [10s] 
                                                        

| Syncing resources... (6617/-, 1122 resources/s) [10s] 
                                                        

/ Syncing resources... (6833/-, 1122 resources/s) [10s] 
                                                        

- Syncing resources... (7077/-, 1122 resources/s) [11s] 
                                                        

\ Syncing resources... (7084/-, 1083 resources/s) [11s] 
                                                        

| Syncing resources... (7084/-, 1083 resources/s) [11s] 
                                                        

/ Syncing resources... (7084/-, 1083 resources/s) [11s] 
                                                        

- Syncing resources... (7084/-, 1083 resources/s) [11s] 
                                                        

\ Syncing resources... (7201/-, 1083 resources/s) [11s] 
                                                        

| Syncing resources... (7382/-, 1083 resources/s) [11s] 
                                                        

/ Syncing resources... (7670/-, 1132 resources/s) [11s] 
                                                        

- Syncing resources... (7905/-, 1132 resources/s) [11s] 
                                                        

\ Syncing resources... (8080/-, 1132 resources/s) [11s] 
                                                        

| Syncing resources... (8080/-, 1132 resources/s) [12s] 
                                                        

/ Syncing resources... (8080/-, 1132 resources/s) [12s] 
                                                        

- Syncing resources... (8080/-, 1132 resources/s) [12s] 
                                                        

\ Syncing resources... (8080/-, 1080 resources/s) [12s] 
                                                        

| Syncing resources... (8216/-, 1080 resources/s) [12s] 
                                                        

/ Syncing resources... (8360/-, 1080 resources/s) [12s] 
                                                        

- Syncing resources... (8575/-, 1080 resources/s) [12s] 
                                                        

\ Syncing resources... (8805/-, 1080 resources/s) [12s] 
                                                        

| Syncing resources... (9022/-, 1164 resources/s) [12s] 
                                                        

/ Syncing resources... (9080/-, 1164 resources/s) [12s] 
                                                        

- Syncing resources... (9080/-, 1164 resources/s) [13s] 
                                                        

\ Syncing resources... (9080/-, 1164 resources/s) [13s] 
                                                        

| Syncing resources... (9080/-, 1164 resources/s) [13s] 
                                                        

/ Syncing resources... (9080/-, 1164 resources/s) [13s] 
                                                        

- Syncing resources... (9325/-, 1134 resources/s) [13s] 
                                                        

\ Syncing resources... (9555/-, 1134 resources/s) [13s] 
                                                        

| Syncing resources... (9751/-, 1134 resources/s) [13s] 
                                                        

/ Syncing resources... (9953/-, 1134 resources/s) [13s] 
                                                        

- Syncing resources... (10084/-, 1134 resources/s) [13s] 
                                                         

\ Syncing resources... (10084/-, 1093 resources/s) [13s] 
                                                         

| Syncing resources... (10084/-, 1093 resources/s) [14s] 
                                                         

/ Syncing resources... (10084/-, 1093 resources/s) [14s] 
                                                         

- Syncing resources... (10084/-, 1093 resources/s) [14s] 
                                                         

\ Syncing resources... (10170/-, 1093 resources/s) [14s] 
                                                         

| Syncing resources... (10409/-, 1093 resources/s) [14s] 
                                                         

/ Syncing resources... (10633/-, 1145 resources/s) [14s] 
                                                         

- Syncing resources... (10839/-, 1145 resources/s) [14s] 
                                                         

\ Syncing resources... (11056/-, 1145 resources/s) [14s] 
                                                         

| Syncing resources... (11085/-, 1145 resources/s) [14s] 
                                                         

/ Syncing 2023-07-25T16:19:43.558077312Z panic: arrow/array: column "month" type mismatch: got=utf8, want=date64
... 
... goroutine 26 [running]:
... github.com/apache/arrow/go/v13/arrow/array.NewRecord(0xc00c3917a0, {0xc00c3c50e0, 0xa, 0xc00c3c3800?}, 0x1)
...     /go/pkg/mod/github.com/cloudquery/arrow/go/v13@v13.0.0-20230710001530-a2a76ebbb85f/arrow/array/record.go:151 +0x173
... github.com/cloudquery/cloudquery/plugins/destination/duckdb/client.transformRecord(0x2a60570?, {0x2a795f0, 0xc00080d2c0})
...     /__w/cloudquery/cloudquery/plugins/destination/duckdb/client/transform.go:15 +0xf3
... github.com/cloudquery/cloudquery/plugins/destination/duckdb/client.writeTMPFile(0xc0004b6a50, {0xc000820000, 0x4, 0xc00081f860?})
...     /__w/cloudquery/cloudquery/plugins/destination/duckdb/client/write.go:195 +0x3ae
... github.com/cloudquery/cloudquery/plugins/destination/duckdb/client.(*Client).WriteTableBatch(0xc000474d10, {0x2a63008, 0xc0003f7680}, {0xc0007feba0, 0x14}, {0xc000820000?, 0x4, 0x3e8})
...     /__w/cloudquery/cloudquery/plugins/destination/duckdb/client/write.go:133 +0xd6
... github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).flushTable(0xc00013a100, {0x2a63008, 0xc0003f7680}, {0xc0007feba0, 0x14}, {0xc000820000, 0x4, 0x3e8})
...     /go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.6.1-rc1/writers/batchwriter/batchwriter.go:164 +0xb4
... github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).worker(0xc00013a100, {0x2a63008, 0xc0003f7680}, {0xc0007feba0, 0x14}, 0xc000102840, 0xc0001028a0)
...     /go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.6.1-rc1/writers/batchwriter/batchwriter.go:144 +0x209
... github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).startWorker.func1()
...     /go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.6.1-rc1/writers/batchwriter/batchwriter.go:320 +0x76
... created by github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).startWorker
...     /go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.6.1-rc1/writers/batchwriter/batchwriter.go:318 +0x3eb
... resources... (11085/-, 1145 resources/s) [14s] 
                                                         

- Syncing resources... (11085/-, 1145 resources/s) [15s] 
                                                         

\ Syncing resources... (11085/-, 1065 resources/s) [15s] 
                                                         

| Syncing resources... (11156/-, 1065 resources/s) [15s] 
                                                         

/ Syncing resources... (11403/-, 1065 resources/s) [15s] 
                                                         

- Syncing resources... (11603/-, 1065 resources/s) [15s] 
                                                         

\ Syncing resources... (11822/-, 1065 resources/s) [15s] 
                                                         

| Syncing resources... (12078/-, 1138 resources/s) [15s] 
                                                         

/ Syncing resources... (12086/-, 1138 resources/s) [15s] 
                                                         

- Syncing resources... (12086/-, 1138 resources/s) [15s] 
                                                         

\ Syncing resources... (12086/-, 1138 resources/s) [15s] 
                                                         

| Syncing resources... (12086/-, 1138 resources/s) [16s] 
                                                         

/ Syncing resources... (12182/-, 1138 resources/s) [16s] 
                                                         

- Syncing resources... (12388/-, 1137 resources/s) [16s] 
                                                         

\ Syncing resources... (12631/-, 1137 resources/s) [16s] 
                                                         

| Syncing resources... (12764/-, 1137 resources/s) [16s] 
                                                         

/ Syncing resources... (12895/-, 1137 resources/s) [16s] 
                                                         

- Syncing resources... (13152/-, 1137 resources/s) [16s] 
                                                         

\ Syncing resources... (13372/-, 1137 resources/s) [16s] 
                                                         

| Syncing resources... (13543/-, 1164 resources/s) [16s] 
                                                         

/ Syncing resources... (13752/-, 1164 resources/s) [16s] 
                                                         

- Syncing resources... (13996/-, 1164 resources/s) [17s] 
                                                         

\ Syncing resources... (14253/-, 1164 resources/s) [17s] 
                                                         

| Syncing resources... (14673/-, 1164 resources/s) [17s] 
                                                         

/ Syncing resources... (14959/-, 1347 resources/s) [17s] 
                                                         

- Syncing resources... (15296/-, 1347 resources/s) [17s] 
                                                         

\ Syncing resources... (15489/-, 1347 resources/s) [17s] 
                                                         

| Syncing resources... (15723/-, 1347 resources/s) [17s] 
                                                         

/ Syncing resources... (15866/-, 1347 resources/s) [17s] 
                                                         

- Syncing resources... (15866/-, 1347 resources/s) [17s] 
                                                         

\ Syncing resources... (15866/-, 1431 resources/s) [17s] 
                                                         

| Syncing resources... (15866/-, 1431 resources/s) [18s] 
                                                         

/ Syncing resources... (16091/-, 1431 resources/s) [18s] 
                                                         

- Syncing resources... (16369/-, 1431 resources/s) [18s] 
                                                         

\ Syncing resources... (16593/-, 1431 resources/s) [18s] 
                                                         

| Syncing resources... (16776/-, 1431 resources/s) [18s] 
                                                         

/ Syncing resources... (16867/-, 1411 resources/s) [18s] 
                                                         

- Syncing resources... (16867/-, 1411 resources/s) [18s] 
                                                         

\ Syncing resources... (16867/-, 1411 resources/s) [18s] 
                                                         

| Syncing resources... (16867/-, 1411 resources/s) [18s] 
                                                         

/ Syncing resources... (17130/-, 1411 resources/s) [18s] 
                                                         

- Syncing resources... (17475/-, 1411 resources/s) [19s] 
                                                         

\ Syncing resources... (17682/-, 1496 resources/s) [19s] 
                                                         

| Syncing resources... (17861/-, 1496 resources/s) [19s] 
                                                         

/ Syncing resources... (17861/-, 1496 resources/s) [19s] 
                                                         

- Syncing resources... (17861/-, 1496 resources/s) [19s] 
                                                         

\ Syncing resources... (17861/-, 1496 resources/s) [19s] 
                                                         

| Syncing resources... (18002/-, 1408 resources/s) [19s] 
                                                         

/ Syncing resources... (18341/-, 1408 resources/s) [19s] 
                                                         

- Syncing resources... (18517/-, 1408 resources/s) [19s] 
                                                         

\ Syncing resources... (18736/-, 1408 resources/s) [19s] 
                                                         

| Syncing resources... (19016/-, 1408 resources/s) [20s] 
                                                         

/ Syncing resources... (19277/-, 1569 resources/s) [20s] 
                                                         

- Syncing resources... (19301/-, 1569 resources/s) [20s] 
                                                         

\ Syncing resources... (19301/-, 1569 resources/s) [20s] 
                                                         

| Syncing resources... (19301/-, 1569 resources/s) [20s] 
                                                         

/ Syncing resources... (19301/-, 1569 resources/s) [20s] 
                                                         

- Syncing resources... (19301/-, 1569 resources/s) [20s] 
                                                         

\ Syncing resources... (19572/-, 1543 resources/s) [20s] 
                                                         

| Syncing resources... (19819/-, 1543 resources/s) [20s] 
                                                         

/ Syncing resources... (20101/-, 1543 resources/s) [20s] 
                                                         

- Syncing resources... (20296/-, 1543 resources/s) [21s] 
                                                         

\ Syncing resources... (20296/-, 1543 resources/s) [21s] 
                                                         

| Syncing resources... (20296/-, 1543 resources/s) [21s] 
                                                         

/ Syncing resources... (20296/-, 1468 resources/s) [21s] 
                                                         

- Syncing resources... (20296/-, 1468 resources/s) [21s] 
                                                         

\ Syncing resources... (20398/-, 1468 resources/s) [21s] 
                                                         

| Syncing resources... (20608/-, 1468 resources/s) [21s] 
                                                         

/ Syncing resources... (20870/-, 1468 resources/s) [21s] 
                                                         

- Syncing resources... (21139/-, 1468 resources/s) [21s] 
                                                         

\ Syncing resources... (21300/-, 1583 resources/s) [21s] 
                                                         

| Syncing resources... (21300/-, 1583 resources/s) [22s] 
                                                         

/ Syncing resources... (21300/-, 1583 resources/s) [22s] 
                                                         

- Syncing resources... (21300/-, 1583 resources/s) [22s] 
                                                         

\ Syncing resources... (21300/-, 1583 resources/s) [22s] 
                                                         

| Syncing resources... (21456/-, 1420 resources/s) [22s] 
                                                         

/ Syncing resources... (21647/-, 1420 resources/s) [22s] 
                                                         

- Syncing resources... (21906/-, 1420 resources/s) [22s] 
                                                         

\ Syncing resources... (22145/-, 1420 resources/s) [22s] 
                                                         

| Syncing resources... (22300/-, 1420 resources/s) [22s] 
                                                         

/ Syncing resources... (22300/-, 1420 resources/s) [22s] 
                                                         

- Syncing resources... (22300/-, 1280 resources/s) [23s] 
                                                         

\ Syncing resources... (22300/-, 1280 resources/s) [23s] 
                                                         

| Syncing resources... (22300/-, 1280 resources/s) [23s] 
                                                         

/ Syncing resources... (22503/-, 1280 resources/s) [23s] 
                                                         

- Syncing resources... (22757/-, 1280 resources/s) [23s] 
                                                         

\ Syncing resources... (23023/-, 1280 resources/s) [23s] 
                                                         

| Syncing resources... (23216/-, 1281 resources/s) [23s] 
                                                         

/ Syncing resources... (23301/-, 1281 resources/s) [23s] 
                                                         

- Syncing resources... (23301/-, 1281 resources/s) [23s] 
                                                         

\ Syncing resources... (23301/-, 1281 resources/s) [23s] 
                                                         

| Syncing resources... (23301/-, 1281 resources/s) [24s] 
                                                         

/ Syncing resources... (23301/-, 1281 resources/s) [24s] 
                                                         

- Syncing resources... (23526/-, 1166 resources/s) [24s] 
                                                         

\ Syncing resources... (23822/-, 1166 resources/s) [24s] 
                                                         

| Syncing resources... (23841/-, 1166 resources/s) [24s] 
                                                         

/ Syncing resources... (23841/-, 1166 resources/s) [24s] 
                                                         

- Syncing resources... (23841/-, 1166 resources/s) [24s] 
                                                         

\ Syncing resources... (23841/-, 1166 resources/s) [24s] 
                                                         

| Syncing resources... (23841/-, 1082 resources/s) [24s] 
                                                         

/ Syncing resources... (23975/-, 1082 resources/s) [24s] 
                                                         

- Syncing resources... (24535/-, 1082 resources/s) [25s] source plugin process failed with exit status 2
... Error: failed to sync v3 source ...: write client returned error (insert): error reading from server: read unix @->/tmp/cq-YurmbdZeXIuRNfzf.sock: read: connection reset by peer
```

### CloudQuery version

cloudquery version 3.9.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @nicosuave 👋  https://github.com/cloudquery/cloudquery/pull/12538 should fix this issue

**Comment by nicosuave** [comment]
Thanks @erezrokah, you are always so helpful!

**Comment by erezrokah** [comment]
Release in [`v4.2.0`](https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-duckdb-v4.2.0) 🚀

**Comment by thijsbrouwers** [comment]
I'm experiencing the same when using a `postgresql` database as destination. It creates a column of type `text` instead of `date`.

**Comment by erezrokah** [comment]
Hi @thijsbrouwers, can you open a new issue please via https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E.

Please share your configuration, CLI and plugins versions as instructed by the template
