### ISSUE TITLE
bug: panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by nicosuave** [cloudquery/cloudquery#12556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From Postgres -> DuckDB, I am seeing the error mentioned in the title. A few tables' data makes it over to the destination fine, but I see the error after row 12k on the first table mentioned below.

### Expected Behavior

No failures mid transfer of table

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: ...
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v2.0.3"
  destinations: ["motherduck"]
  tables: ["*"]
  spec:
    connection_string: ...
---
kind: destination
spec:
  name: motherduck
  path: cloudquery/duckdb
  version: "v4.2.0"
  write_mode: overwrite
  spec:
    connection_string: ...
```

### CloudQuery (redacted) logs

```
                                               2023-07-27T16:00:53.035092010Z panic: runtime error: makeslice: cap out of range
... 
... goroutine 40 [running]:
... github.com/cloudquery/cloudquery/plugins/source/postgresql/client.syncTable({0x11f1db0, 0xc0002facf0}, {0x11f98d0, 0xc00049e1c8}, 0xc0003dc580, 0x107375d?)
...     /home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:111 +0x94
... github.com/cloudquery/cloudquery/plugins/source/postgresql/client.(*Client).syncTables(0xc00009a780, {0x11f1db0, 0xc0002facf0}, {0x0, 0x0}, {0xc0000cb680, 0x46, 0x0?}, 0x0?)
...     /home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:100 +0x358
... github.com/cloudquery/cloudquery/plugins/source/postgresql/client.(*Client).Sync(0xc00009a780, {0x11f1db0, 0xc0002facf0}, {{0xc0003cad20, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
...     /home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:58 +0x3b8
... github.com/cloudquery/plugin-sdk/v4/plugin.(*Plugin).Sync(0xc000480ea0?, {0x11f1db0?, 0xc0002facf0?}, {{0xc0003cad20, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
...     /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/plugin/plugin_source.go:93 +0x117
... github.com/cloudquery/plugin-sdk/v4/internal/servers/plugin/v3.(*Server).Sync.func1()
...     /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/internal/servers/plugin/v3/plugin.go:127 +0xa7
... created by github.com/cloudquery/plugin-sdk/v4/internal/servers/plugin/v3.(*Server).Sync
...     /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/internal/servers/plugin/v3/plugin.go:125 +0x2b0
... Error: failed to sync v3 source ...: unexpected error from sync client receive: rpc error: code = Unavailable desc = error reading from server: read unix @->/tmp/cq-rRSJCqwMOeDJptrj.sock: read: connection reset by peer
...           
```

### CloudQuery version

cloudquery version 3.9.0

### Additional Context

Obfuscated problematic tables. Seeing failures mid-transfer on the first table, but including a few after just in case (in case of concurrency reasons)

```sql
CREATE TABLE public.table1 (
    placeholder1 bigint NOT NULL,
    placeholder2 uuid,
    placeholder3 character varying,
    placeholder4 integer,
    placeholder5 character varying,
    placeholder6 uuid,
    placeholder7 character varying,
    placeholder8 character varying,
    placeholder9 character varying,
    placeholder10 jsonb,
    placeholder11 integer DEFAULT 0,
    placeholder12 character varying,
    placeholder13 character varying,
    placeholder14 character varying,
    placeholder15 timestamp without time zone
);

CREATE TABLE public.table2 (
    placeholder16 uuid DEFAULT public.gen_random_uuid() NOT NULL,
    placeholder17 character varying,
    placeholder18 character varying,
    placeholder19 character varying NOT NULL,
    placeholder20 character varying,
    placeholder21 character varying,
    placeholder22 character varying,
    placeholder23 character varying,
    placeholder24 character varying,
    placeholder25 character varying,
    placeholder26 character varying,
    placeholder27 character varying NOT NULL,
    placeholder28 character varying NOT NULL,
    placeholder29 character varying,
    placeholder30 character varying,
    placeholder31 character varying,
    placeholder32 character varying,
    placeholder33 character varying NOT NULL,
    placeholder34 character varying,
    placeholder35 character varying,
    placeholder36 character varying,
    placeholder37 character varying,
    placeholder38 integer,
    placeholder39 integer,
    placeholder40 character varying,
    placeholder41 character varying NOT NULL,
    placeholder42 character varying NOT NULL,
    placeholder43 character varying NOT NULL,
    placeholder44 character varying,
    placeholder45 timestamp without time zone NOT NULL,
    placeholder46 timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.table3 (
    placeholder47 uuid DEFAULT public.gen_random_uuid() NOT NULL,
    placeholder48 character varying NOT NULL,
    placeholder49 timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    placeholder50 timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    placeholder51 uuid NOT NULL,
    placeholder52 jsonb,
    placeholder53 jsonb DEFAULT '{}'::jsonb NOT NULL,
    placeholder54 integer
);
```

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @nicosuave 👋 Can you trying updating the PostgreSQL source plugin to [`v2.0.4`](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-postgresql-v2.0.4). It should have a fix for this issue

**Comment by nicosuave** [comment]
Hello @erezrokah. That did the trick here, thank you very much!
