### ISSUE TITLE
Sync azure (v9.1.0) -> [mssql (v4.3.2)] fails - write client returned error (insert)

### ISSUE THREAD

**Issue by rafaelrodrigues3092** [cloudquery/cloudquery#12577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading the source (azure) and target plugins (mssql), the sync fails with error:

Error: failed to sync v3 source azure: write client returned error (insert): error reading from server: read unix @->C:\Users\rdadmin\AppData\Local\Temp\cq-srPiAsIdsKzFQWEm.sock: wsarecv: An existing connection was forcibly closed by the remote host.

Sync was working before the upgrade with versions azure (v7.1.1) -> [mssql (v3.0.4)]. Database tables and objects are created without issue.

Things already verified:
- SQL Server permissions (login has db_owner on cloudquery database)
- Tables, user-defined table types, and stored procedures are created OK
- There are no user-created dependent objects
- Connection string format (tried different options - see below in config)
- There are other tools accessing the same database server (different database)  from the same location with no issues. Previous versions of plugins were OK.

### Expected Behavior

Expecting a successful sync

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: azure
  path: cloudquery/azure
  version: "v9.1.0"
  destinations: [
    "mssql"
  ]
  concurrency: 100000
  skip_dependent_tables: true
  tables: [
    "azure_advisor_recommendation_metadata",
    "azure_advisor_recommendations",
    "azure_advisor_suppressions",
    "azure_appservice_certificate_orders",
    "azure_appservice_certificates",
    "azure_appservice_deleted_web_apps",
    "azure_appservice_domains",
    "azure_appservice_environments",
    "azure_appservice_plans",
    "azure_appservice_recommendations",
    "azure_appservice_resource_health_metadata",
    "azure_appservice_static_sites",
    "azure_appservice_top_level_domains",
    "azure_appservice_web_apps",
    "azure_appservice_web_app_configurations",
    "azure_appservice_web_app_vnet_connections",
    "azure_compute_availability_sets",
    "azure_compute_capacity_reservation_groups",
    "azure_compute_capacity_reservations",
    "azure_compute_cloud_services",
    "azure_compute_disk_accesses",
    "azure_compute_disk_encryption_sets",
    "azure_compute_disks",
    "azure_compute_galleries",
    "azure_compute_gallery_images",
    "azure_compute_gallery_image_versions",
    "azure_compute_images",
    "azure_compute_restore_point_collections",
    "azure_compute_skus",
    "azure_compute_snapshots",
    "azure_compute_ssh_public_keys",
    "azure_compute_virtual_machine_scale_sets",
    "azure_compute_virtual_machine_scale_set_network_interfaces",
    "azure_compute_virtual_machine_scale_set_vms",
    "azure_compute_virtual_machines",
    "azure_compute_virtual_machine_extensions",
    "azure_compute_virtual_machine_patch_assessments",
    "azure_containerregistry_registries",
    "azure_cosmos_database_accounts",
    "azure_cosmos_mongo_db_databases",
    "azure_cosmos_sql_databases",
    "azure_cosmos_locations",
    "azure_keyvault_keyvault",
    "azure_network_application_gateways",
    "azure_network_interfaces",
    "azure_network_interface_ip_configurations",
    "azure_network_ip_allocations",
    "azure_network_ip_groups",
    "azure_network_load_balancers",
    "azure_network_nat_gateways",
    "azure_network_private_endpoints",
    "azure_network_private_link_services",
    "azure_network_profiles",
    "azure_network_public_ip_addresses",
    "azure_network_public_ip_prefixes",
    "azure_network_route_filters",
    "azure_network_route_tables",
    "azure_network_security_groups",
    "azure_network_security_partner_providers",
    "azure_network_service_endpoint_policies",
    "azure_network_subscription_network_manager_connections",
    "azure_network_virtual_appliances",
    "azure_network_virtual_hubs",
    "azure_network_virtual_network_gateway_connections",
    "azure_network_virtual_network_gateways",
    "azure_network_virtual_network_taps",
    "azure_network_virtual_networks",
    "azure_network_virtual_network_subnets",
    "azure_network_virtual_routers",
    "azure_network_virtual_wans",
    "azure_postgresql_servers",
    "azure_postgresql_databases",
    "azure_sql_instance_pools",
    "azure_sql_managed_instances",
    "azure_sql_servers",
    "azure_sql_server_databases",
    "azure_storage_accounts",
    "azure_subscription_subscriptions",
    "azure_subscription_subscription_locations",
    "azure_subscription_tenants",
    "azure_trafficmanager_profiles"
  ]
  skip_tables: [
    "azure_analysisservices_servers",
    "azure_apimanagement_service",
    "azure_appcomplianceautomation_reports",
    "azure_appconfiguration_configuration_stores",
    "azure_applicationinsights_components",
    "azure_applicationinsights_web_tests",
    "azure_appservice_web_app_auth_settings",
    "azure_authorization_classic_administrators",
    "azure_authorization_provider_operations_metadata",
    "azure_authorization_role_assignments",
    "azure_authorization_role_definitions",
    "azure_automation_account",
    "azure_azurearcdata_postgres_instances",
    "azure_azurearcdata_sql_managed_instances",
    "azure_azurearcdata_sql_server_instances",
    "azure_batch_account",
    "azure_billing_accounts",
    "azure_billing_enrollment_accounts",
    "azure_billing_periods",
    "azure_botservice_bots",
    "azure_cdn_edge_nodes",
    "azure_cdn_managed_rule_sets",
    "azure_cdn_profiles",
    "azure_cdn_endpoints",
    "azure_cdn_rule_sets",
    "azure_cdn_security_policies",
    "azure_cognitiveservices_accounts",
    "azure_cognitiveservices_account_deployments",
    "azure_cognitiveservices_account_models",
    "azure_cognitiveservices_account_private_endpoint_connections",
    "azure_cognitiveservices_account_private_link_resources",
    "azure_cognitiveservices_account_skus",
    "azure_cognitiveservices_account_usages",
    "azure_cognitiveservices_commitment_plans",
    "azure_cognitiveservices_deleted_accounts",
    "azure_cognitiveservices_resource_skus",
    "azure_confluent_marketplace_agreements",
    "azure_connectedvmware_clusters",
    "azure_connectedvmware_datastores",
    "azure_connectedvmware_hosts",
    "azure_connectedvmware_resource_pools",
    "azure_connectedvmware_v_centers",
    "azure_connectedvmware_virtual_machine_templates",
    "azure_connectedvmware_virtual_machines",
    "azure_connectedvmware_virtual_networks",
    "azure_consumption_billing_account_balances",
    "azure_consumption_billing_account_budgets",
    "azure_consumption_billing_account_charges",
    "azure_consumption_billing_account_events",
    "azure_consumption_billing_account_legacy_usage_details",
    "azure_consumption_billing_account_lots",
    "azure_consumption_billing_account_marketplaces",
    "azure_consumption_billing_account_modern_usage_details",
    "azure_consumption_billing_account_reservation_recommendations",
    "azure_consumption_billing_account_tags",
    "azure_consumption_billing_profile_reservation_details",
    "azure_consumption_billing_profile_reservation_recommendations",
    "azure_consumption_billing_profile_reservation_summaries",
    "azure_consumption_billing_profile_reservation_transactions",
    "azure_consumption_subscription_budgets",
    "azure_consumption_subscription_legacy_usage_details",
    "azure_consumption_subscription_marketplaces",
    "azure_consumption_subscription_price_sheets",
    "azure_consumption_subscription_reservation_recommendations",
    "azure_consumption_subscription_tags",
    "azure_containerinstance_container_groups",
    "azure_containerservice_managed_clusters",
    "azure_containerservice_managed_cluster_upgrade_profiles",
    "azure_containerservice_snapshots",
    "azure_cosmos_restorable_database_accounts",
    "azure_costmanagement_views",
    "azure_costmanagement_view_queries",
    "azure_customerinsights_hubs",
    "azure_dashboard_grafana",
    "azure_databox_jobs",
    "azure_datadog_marketplace_agreements",
    "azure_datadog_monitors",
    "azure_datafactory_factories",
    "azure_datalakeanalytics_accounts",
    "azure_datalakestore_accounts",
    "azure_datamigration_services",
    "azure_desktopvirtualization_host_pools",
    "azure_devhub_workflow",
    "azure_devops_pipeline_template_definitions",
    "azure_dns_zones",
    "azure_dns_record_sets",
    "azure_dnsresolver_dns_forwarding_rulesets",
    "azure_dnsresolver_dns_resolvers",
    "azure_elastic_monitors",
    "azure_engagementfabric_accounts",
    "azure_eventgrid_topic_types",
    "azure_eventhub_namespaces",
    "azure_eventhub_namespace_network_rule_sets",
    "azure_frontdoor_front_doors",
    "azure_frontdoor_managed_rule_sets",
    "azure_frontdoor_network_experiment_profiles",
    "azure_hanaonazure_sap_monitors",
    "azure_hdinsight_clusters",
    "azure_healthbot_bots",
    "azure_healthcareapis_services",
    "azure_hybridcompute_private_link_scopes",
    "azure_hybriddatamanager_data_managers",
    "azure_keyvault_keyvault_keys",
    "azure_keyvault_keyvault_secrets",
    "azure_keyvault_keyvault_managed_hsms",
    "azure_kusto_clusters",
    "azure_logic_workflows",
    "azure_maintenance_configurations",
    "azure_maintenance_public_maintenance_configurations",
    "azure_managementgroups_management_groups",
    "azure_mariadb_servers",
    "azure_mariadb_server_configurations",
    "azure_marketplace_private_store",
    "azure_monitor_activity_log_alerts",
    "azure_monitor_autoscale_settings",
    "azure_monitor_log_profiles",
    "azure_monitor_private_link_scopes",
    "azure_monitor_resources",
    "azure_monitor_diagnostic_settings",
    "azure_monitor_subscription_diagnostic_settings",
    "azure_monitor_tenant_activity_log_alerts",
    "azure_monitor_tenant_activity_logs",
    "azure_mysql_servers",
    "azure_mysql_server_configurations",
    "azure_mysql_server_databases",
    "azure_mysqlflexibleservers_servers",
    "azure_network_application_security_groups",
    "azure_network_azure_firewall_fqdn_tags",
    "azure_network_azure_firewalls",
    "azure_network_bastion_hosts",
    "azure_network_bgp_service_communities",
    "azure_network_custom_ip_prefixes",
    "azure_network_ddos_protection_plans",
    "azure_network_dscp_configuration",
    "azure_network_express_route_circuits",
    "azure_network_express_route_circuit_authorizations",
    "azure_network_express_route_circuit_peerings",
    "azure_network_express_route_gateways",
    "azure_network_express_route_ports",
    "azure_network_express_route_ports_locations",
    "azure_network_express_route_service_providers",
    "azure_network_firewall_policies",
    "azure_network_vpn_gateways",
    "azure_network_vpn_server_configurations",
    "azure_network_vpn_sites",
    "azure_network_watchers",
    "azure_network_watcher_flow_logs",
    "azure_network_web_application_firewall_policies",
    "azure_networkfunction_azure_traffic_collectors_by_subscription",
    "azure_nginx_deployments",
    "azure_notificationhubs_namespaces",
    "azure_operationalinsights_clusters",
    "azure_operationalinsights_workspaces",
    "azure_peering_service_countries",
    "azure_peering_service_locations",
    "azure_peering_service_providers",
    "azure_policy_assignments",
    "azure_policy_data_policy_manifests",
    "azure_policy_definitions",
    "azure_policy_exemptions",
    "azure_policy_set_definitions",
    "azure_portal_list_tenant_configuration_violations",
    "azure_portal_tenant_configurations",
    "azure_postgresql_server_configurations",
    "azure_postgresql_server_firewall_rules",
    "azure_postgresqlflexibleservers_servers",
    "azure_postgresqlhsc_server_groups",
    "azure_powerbidedicated_capacities",
    "azure_privatedns_private_zones",
    "azure_privatedns_private_zone_record_sets",
    "azure_privatedns_private_zone_virtual_network_links",
    "azure_providerhub_provider_registrations",
    "azure_redhatopenshift_open_shift_clusters",
    "azure_redis_caches",
    "azure_relay_namespaces",
    "azure_reservations_reservation",
    "azure_reservations_reservation_order",
    "azure_resources_links",
    "azure_resources_resource_groups",
    "azure_resources_resources",
    "azure_saas_resources",
    "azure_search_services",
    "azure_security_alerts",
    "azure_security_alerts_suppression_rules",
    "azure_security_allowed_connections",
    "azure_security_applications",
    "azure_security_assessments",
    "azure_security_sub_assessments",
    "azure_security_assessments_metadata",
    "azure_security_auto_provisioning_settings",
    "azure_security_automations",
    "azure_security_connectors",
    "azure_security_contacts",
    "azure_security_discovered_security_solutions",
    "azure_security_external_security_solutions",
    "azure_security_governance_rule",
    "azure_security_jit_network_access_policies",
    "azure_security_locations",
    "azure_security_pricings",
    "azure_security_regulatory_compliance_standards",
    "azure_security_secure_score_control_definitions",
    "azure_security_secure_score_controls",
    "azure_security_secure_scores",
    "azure_security_settings",
    "azure_security_solutions",
    "azure_security_tasks",
    "azure_security_topology",
    "azure_security_workspace_settings",
    "azure_servicebus_namespaces",
    "azure_servicebus_namespace_topics",
    "azure_servicebus_namespace_topic_authorization_rules",
    "azure_servicebus_namespace_topic_rule_access_keys",
    "azure_sql_managed_instance_encryption_protectors",
    "azure_sql_managed_instance_vulnerability_assessments",
    "azure_sql_server_admins",
    "azure_sql_server_advanced_threat_protection_settings",
    "azure_sql_server_blob_auditing_policies",
    "azure_sql_server_database_blob_auditing_policies",
    "azure_sql_server_database_long_term_retention_policies",
    "azure_sql_server_database_threat_protections",
    "azure_sql_server_database_vulnerability_assessments",
    "azure_sql_server_database_vulnerability_assessment_scans",
    "azure_sql_transparent_data_encryptions",
    "azure_sql_server_encryption_protectors",
    "azure_sql_server_firewall_rules",
    "azure_sql_server_security_alert_policies",
    "azure_sql_server_virtual_network_rules",
    "azure_sql_server_vulnerability_assessments",
    "azure_sql_virtual_clusters",
    "azure_sqlvirtualmachine_groups",
    "azure_sqlvirtualmachine_sql_virtual_machines",
    "azure_storage_blob_services",
    "azure_storage_containers",
    "azure_storage_file_shares",
    "azure_storage_queue_services",
    "azure_storage_queues",
    "azure_storage_queue_acl",
    "azure_storage_tables",
    "azure_storagecache_caches",
    "azure_streamanalytics_streaming_jobs",
    "azure_support_services",
    "azure_support_tickets",
    "azure_synapse_private_link_hubs",
    "azure_synapse_workspaces",
    "azure_windowsiot_services",
    "azure_workloads_monitors"
  ]
  spec:
    cloud_name: 'AzurePublic'
    discovery_concurrency: 100
    subscriptions: [
		(23 subscriptions)
    ]
---
kind: destination
spec:
 name: "mssql"
 registry: "github"
 path: "cloudquery/mssql"
 version: "v4.3.2"
 migrate_mode: "forced"
 spec:
  connection_string: "sqlserver://<login_name>:<password>@<fqdn_server_name>:1433?database=cloudquery&connection+timeout=60&encrypt=true;trustServerCertificate=false&hostNameInCertificate=*.domain_name;log=255"
  #connection_string: "sqlserver://<login_name>:<password>@<fqdn_server_name>:1433?database=cloudquery&connection+timeout=60;log=255"
  auth_mode: ms
  schema: dbo

```	

### Steps To Reproduce

1. Source: Windows VM (4vCPUs, 32GB memory)
2. Destination: Azure SQL Managed Instance
3. Using config listed above
4.  Run sync azure (v9.1.0) -> [mssql (v4.3.2)]

### CloudQuery (redacted) logs

progress:
```
...
/ Syncing resources... (1176/-, 0 resources/hr) [42s] 
- Syncing resources... (1176/-, 0 resources/hr) [43s] 
\ Syncing resources... (1176/-, 0 resources/hr) [43s] 
| Syncing resources... (1176/-, 0 resources/hr) [43s] 
                                                        
```

stdout:
```
{"level":"warn","module":"cli","source":"azure","field":"concurrency","time":"2023-07-28T15:01:53Z","message":"the top-level `concurrency` option is deprecated. Please use the plugin-level concurrency option instead"}
{"level":"error","module":"cli","error":"TerminateProcess: Access is denied.","time":"2023-07-28T15:02:39Z","message":"failed to kill source plugin"}
{"level":"error","module":"cli","error":"failed to sync v3 source azure: write client returned error (insert): error reading from server: read unix @->C:\\Users\\rdadmin\\AppData\\Local\\Temp\\cq-srPiAsIdsKzFQWEm.sock: wsarecv: An existing connection was forcibly closed by the remote host.","time":"2023-07-28T15:02:39Z","message":"exiting with error"}
```

stderr:
```
panic: runtime error: index out of range [1] with length 1

goroutine 377 [running]:
github.com/apache/arrow/go/v13/arrow/array.(*Timestamp).Value(...)
	/home/runner/go/pkg/mod/github.com/cloudquery/arrow/go/v13@v13.0.0-20230723001421-10df4b9d1986/arrow/array/timestamp.go:54
github.com/cloudquery/cloudquery/plugins/destination/mssql/queries.getColValue({0x116cb60, 0xc000819600}, 0x1)
	/home/runner/work/cloudquery/cloudquery/plugins/destination/mssql/queries/values.go:87 +0xa57
github.com/cloudquery/cloudquery/plugins/destination/mssql/queries.GetRows({0x11687e0, 0xc002d22300})
	/home/runner/work/cloudquery/cloudquery/plugins/destination/mssql/queries/values.go:19 +0x1e5
github.com/cloudquery/cloudquery/plugins/destination/mssql/queries.TVPQuery({0xc0007826d1, 0x3}, 0xc000141080, {0xc000700000, 0xe1, 0xe1})
	/home/runner/work/cloudquery/cloudquery/plugins/destination/mssql/queries/tvp.go:72 +0x94
github.com/cloudquery/cloudquery/plugins/destination/mssql/client.(*Client).insertTVP(0xc000792240, {0x11642b0, 0xc000038040}, 0x2?, {0xc000700000?, 0xc0005efd18?, 0x449134?})
	/home/runner/work/cloudquery/cloudquery/plugins/destination/mssql/client/tvp.go:48 +0x57
github.com/cloudquery/cloudquery/plugins/destination/mssql/client.(*Client).WriteTableBatch(0xc000792240, {0x11642b0, 0xc000038040}, {0xc00005fdc8?, 0xc00005fe88?}, {0xc000a84000, 0xe1, 0x362?})
	/home/runner/work/cloudquery/cloudquery/plugins/destination/mssql/client/write.go:30 +0x26b
github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).flushTable(0xc00012a100, {0x11642b0, 0xc000038040}, {0xc000036920, 0x1f}, {0xc000a84000, 0xe1, 0x3e8})
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/writers/batchwriter/batchwriter.go:169 +0xb4
github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).worker(0xc00012a100, {0x11642b0, 0xc000038040}, {0xc000036920, 0x1f}, 0xc00088b2c0, 0xc00088b320)
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/writers/batchwriter/batchwriter.go:147 +0x2ff
github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).startWorker.func1()
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/writers/batchwriter/batchwriter.go:300 +0x7c
created by github.com/cloudquery/plugin-sdk/v4/writers/batchwriter.(*BatchWriter).startWorker
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.2.3/writers/batchwriter/batchwriter.go:296 +0x3ea
Error: failed to sync v3 source azure: write client returned error (insert): error reading from server: read unix @->C:\Users\rdadmin\AppData\Local\Temp\cq-srPiAsIdsKzFQWEm.sock: wsarecv: An existing connection was forcibly closed by the remote host.

```

### CloudQuery version

cloudquery version 3.11.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @rafaelrodrigues3092 👋 Thank you for reporting the issue. Do you mind trying with [`v4.3.3`](https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-mssql-v4.3.3) of the MSSQL plugin? It should fix the issue

**Comment by rafaelrodrigues3092** [comment]
hi @erezrokah 
Thank you for taking a look at this issue.

I tried version 4.3.3 and I am now facing a new issue
```
{"level":"error","module":"cli","grpc.code":"Internal","grpc.component":"server","grpc.error":"rpc error: code = Internal desc = write failed: read tcp 10.XX.XX.XX:55081->10.16.244.142:11005: i/o timeout","grpc.method":"Write","grpc.method_type":"client_stream","grpc.service":"cloudquery.plugin.v3.Plugin","grpc.start_time":"2023-07-31T20:35:30Z","grpc.time_ms":"2.5734995e+06","message":"finished call","peer.address":"@","protocol":"grpc","time":"2023-07-31T21:18:24Z"}
{"level":"error","module":"cli","error":"failed to sync v3 source azure: rpc error: code = Internal desc = write failed: read tcp 10.XX.XX.XX:55081->10.YY.YY.YY:11005: i/o timeout","time":"2023-07-31T21:18:24Z","message":"exiting with error"}
```

thank you

**Comment by erezrokah** [comment]
Hi @rafaelrodrigues3092, thanks for sharing. That might related to memory/concurrency issues.
Can you try a lower value of `concurrency`, e.g.

```yaml
kind: source
spec:
  name: azure
  path: cloudquery/azure
  version: "v9.1.0"
  ...
  spec:
    ...
    concurrency: 1000
```

and also env variables to authenticate, see more in https://www.cloudquery.io/docs/plugins/sources/azure/overview#authentication

**Comment by erezrokah** [comment]
Glad it's working and thank you for the feedback ❤️
