### ISSUE TITLE
Panic on debugging yandex cloud provider

### ISSUE THREAD

**Issue by daniil-ushkov** [cloudquery/cloudquery#177]
I try to run yandex cloud plugin in debug mode with `config.hcl`:
```
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "yandex-cloud/yandex" {
    source  = "yandex-cloud"
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=pass database=postgres port=5432"
  }
}

// All Provider Configurations

provider "yandex" {
  configuration {
    // Optional. Filter as described https://cloud.yandex.com/docs/resource-manager/grpc/folder_service#List
    // folder_filter = ""
    // Optional. If not specified either using all folders accessible.
    // folder_ids = [<CHANGE_THIS_TO_YOUR_FOLDER_ID>]
    cloud_id = "<my_cloud_id>"
  }
  resources = [
    "compute.disks"
  ]
}
```

it panics with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b3a1ad]

goroutine 101 [running]:
github.com/cloudquery/cloudquery/pkg/ui/console.buildFetchProgress.func2(0xc000114a90, 0x6, 0x1d96b7a, 0x9, 0xc00045b560, 0xb3, 0x0, 0x0)
        /home/runner/work/cloudquery/cloudquery/pkg/ui/console/client.go:163 +0xad
github.com/cloudquery/cloudquery/pkg/client.(*Client).Fetch.func1(0x0, 0x0)
        /home/runner/work/cloudquery/cloudquery/pkg/client/client.go:257 +0x1069
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002a7110, 0xc0000cc930)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Comment by roneli** [comment]
Hi,  @daniil-ushkov  thanks for reporting this issue.

I will check into this panic.

In the meantime I suggest running cloudquery with --enable-console-log, it will override the console UI.
