### ISSUE TITLE
bug(tests): Sporadically failing AWS test

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2474]
This error occurred in CI, but I was unable to reproduce it locally:

```
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/firehose.buildKinesisFirehoses(_, _)
	/home/runner/work/cloudquery/cloudquery/plugins/source/aws/resources/services/firehose/delivery_streams_mock_test.go:33 +0x5c7
github.com/cloudquery/cloudquery/plugins/source/aws/client.AwsMockTestHelper.func1({_, _}, {{0xc9cd60, 0xc000558bf0}, 0x0, {0x0, 0x0}, {0xc0005fe000, 0x1, 0x1f4}, ...}, ...)
	/home/runner/work/cloudquery/cloudquery/plugins/source/aws/client/testing.go:33 +0x222
github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).Sync(_, {_, _}, {{0xc9cd60, 0xc000558bf0}, 0x0, {0x0, 0x0}, {0xc0005fe000, 0x1, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.12.7/plugins/source.go:107 +0xbc
github.com/cloudquery/plugin-sdk/plugins.TestSourcePluginSync.func1()
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.12.7/plugins/source_testing.go:37 +0xe7
created by github.com/cloudquery/plugin-sdk/plugins.TestSourcePluginSync
```

**Comment by yevgenypats** [comment]
We shouldn't use `"github.com/bxcodec/faker"` anymore but our own which is available in the SDK and is not storing configuration parameters as global variables.

**Comment by bbernays** [comment]
I am not sure I follow... What config params are you referring to?

**Comment by yevgenypats** [comment]
Opened an issue - https://github.com/cloudquery/cloudquery/issues/2492
