### ISSUE TITLE
Index out of range on policy run

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#314]
### Describe the Bug
Running `cloudquery policy run aws` gives the following:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cloudquery/cloudquery/pkg/policy.decodePolicyContent({0xc000eb3420, 0x1, 0xc0003e28f0}, 0xc000728420, 0x1e635c0, 0xc000295080)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/parser.go:101 +0x12e5
github.com/cloudquery/cloudquery/pkg/policy.decodePolicyBlock(0xc0001752b0, 0xc0003e28f0)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/parser.go:159 +0xf4
github.com/cloudquery/cloudquery/pkg/policy.decodePolicyContent({0xc000eb33a0, 0x1, 0x1ec7680}, 0xc000728300, 0xc000db5388, 0xc000294ec0)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/parser.go:119 +0xdf6
github.com/cloudquery/cloudquery/pkg/policy.decodePolicyBlock(0xc000127e10, 0x24)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/parser.go:159 +0xf4
github.com/cloudquery/cloudquery/pkg/policy.DecodePolicies({0x22d9850, 0xc0003e2b00}, {0x0, 0x0, 0x0}, {0xc00063f080, 0x24})
        /home/runner/work/cloudquery/cloudquery/pkg/policy/parser.go:31 +0x246
github.com/cloudquery/cloudquery/pkg/policy.decodePolicy({0x22d9850, 0xc0003e2b00}, {0x0, 0x0, 0xc000d455a0}, {0xc00063f080, 0xc000da5880})
        /home/runner/work/cloudquery/cloudquery/pkg/policy/manager.go:487 +0x3a
github.com/cloudquery/cloudquery/pkg/policy.readPolicy({0xc0006532f0, 0x2f}, {0xc00063f080, 0x24})
        /home/runner/work/cloudquery/cloudquery/pkg/policy/manager.go:482 +0xcc
github.com/cloudquery/cloudquery/pkg/policy.(*ManagerImpl).loadRemotePolicy(0xc00031d320, {0x22d91f8, 0xc00003a9c0}, 0xc000592240, 0xc0006161e0)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/manager.go:275 +0x410
github.com/cloudquery/cloudquery/pkg/policy.(*ManagerImpl).Load(0xc000577050, {0x22d91f8, 0xc00003a9c0}, 0xc000616200, 0xc00029a0c0)
        /home/runner/work/cloudquery/cloudquery/pkg/policy/manager.go:190 +0x134
github.com/cloudquery/cloudquery/pkg/client.(*Client).runPolicy(0xc00014f0e0, {0x22d91f8, 0xc00003a9c0}, 0xc0005a00a0, 0xc000db59f0)
        /home/runner/work/cloudquery/cloudquery/pkg/client/client.go:643 +0x283
github.com/cloudquery/cloudquery/pkg/client.(*Client).RunPolicies(0xc00014f0e0, {0x22d91f8, 0xc00003a9c0}, 0xc000db59f0)
        /home/runner/work/cloudquery/cloudquery/pkg/client/client.go:585 +0xec
github.com/cloudquery/cloudquery/pkg/ui/console.Client.RunPolicies({0xc00014f0e0, 0xc00014c360, 0xc000208d20}, {0x22d91f8, 0xc00003a9c0}, {0xc00060fb20, 0x1, 0x1}, {0x0, 0x0}, ...)
        /home/runner/work/cloudquery/cloudquery/pkg/ui/console/client.go:183 +0x4f7
github.com/cloudquery/cloudquery/cmd.glob..func7({0x22d91f8, 0xc00003a9c0}, 0x8b, 0x0, {0xc00060fb20, 0x1, 0x1})
        /home/runner/work/cloudquery/cloudquery/cmd/policy_run.go:27 +0x145
github.com/cloudquery/cloudquery/cmd.handleConsole({0x22d92a0, 0xc0002025d0}, 0xc0001a6900, 0xc000191540, {0xc00060fb20, 0x1, 0x1}, 0x2037088)
        /home/runner/work/cloudquery/cloudquery/cmd/util.go:88 +0x2e4
github.com/cloudquery/cloudquery/cmd.handleCommand.func1(0x2c93b00, {0xc00060fb20, 0x1, 0x1})
        /home/runner/work/cloudquery/cloudquery/cmd/util.go:41 +0x455
github.com/spf13/cobra.(*Command).execute(0x2c93b00, {0xc00060faf0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2c94a00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudquery/cloudquery/cmd.Execute()
        /home/runner/work/cloudquery/cloudquery/cmd/root.go:89 +0x25
main.main()
        /home/runner/work/cloudquery/cloudquery/main.go:16 +0x5b
```

**Comment by disq** [comment]
Two-fold issue:
- AWS `policy.hcl` had a bug at the top level. [Fixed in main](https://github.com/cloudquery-policies/aws/commit/0da6a69ad76c572b6275efbef7c3c0e30f29bcb2) so if you `rm -rf .cq/policies/` this will make it fetch it again and it'll magically work.
- Policy parser had some assumptions about having valid policy blocks. [Fixed in PR](https://github.com/cloudquery/cloudquery/pull/315)
