### ISSUE TITLE
Test: Sporadic test failure in k8s plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3627]
The k8s plugin tests are failing (sometimes), visit https://github.com/cloudquery/cloudquery/actions/runs/3403922361/jobs/5660794100#step:7:24

error:
```
Nov  6 10:19:49.000000 ERR column resolver finished with panic error={} client=testContext column=status_last_schedule_time duration=0.097301 stack="failed to set column status_last_schedule_time: cannot parse 2110-10-19 08:53:50.21670207 +0000 UTC m=+2775422040.494306874 as Timestamptz
goroutine 15 [running]:
runtime/debug.Stack()
    /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).resolveColumn.func1()
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/plugins/source_scheduler_dfs.go:186 +0x86
panic({0x15afec0, 0xc0001bf520})
    /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/cloudquery/plugin-sdk/schema.(*Resource).Set(0xc0001c2400?, {0x17a1087, 0x19}, {0x1786d00?, 0xc000013110?})
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/schema/resource.go:146 +0x155
github.com/cloudquery/plugin-sdk/schema.PathResolver.func1({0xc0001c09a0?, 0xc000083a38?}, {0x19ae000?, 0xc0004b8820?}, 0xc0001c2400, {{0x17a1087, 0x19}, 0x9, {0x0, 0x0}, ...})
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/schema/resolvers.go:17 +0x73
github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).resolveColumn(0xc0004280d0, {0x19c3af8, 0xc0001ec480}, {{0x19b7558, 0xc00047e030}, 0x0, {0x0, 0x0}, {0xc0004c5800, 0x35, ...}, ...}, ...)
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/plugins/source_scheduler_dfs.go:193 +0x1cd
github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).resolveResource(0xc0004280d0, {0x19c3ac0?, 0xc00004a0f8?}, 0xc000481000, {0x19ae000, 0xc0004b8820}, 0x0?, {0x168b3c0, 0xc00029c000})
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/plugins/source_scheduler_dfs.go:169 +0x805
github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).resolveResourcesDfs.func1.1()
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/plugins/source_scheduler_dfs.go:124 +0x105
created by github.com/cloudquery/plugin-sdk/plugins.(*SourcePlugin).resolveResourcesDfs.func1
    /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v0.13.20/plugins/source_scheduler_dfs.go:120 +0xf6
" table=k8s_batch_cron_jobs
```

**Comment by erezrokah** [comment]
GitHub too https://github.com/cloudquery/cloudquery/actions/runs/3404028346/jobs/5660964474#step:7:29
