### ISSUE TITLE
Bug: Panic when db not found

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#616]
### Describe the Bug
This related only to `dev` branch which should be merged soon.

running the following with no db produce the following panic

```
yevgenyp@yevgenys-mbp cloudquery % ./cloudquery fetch
Anonymous telemetry collection and crash reporting enabled. Run with --no-telemetry to disable, or check docs at https://docs.cloudquery.io/docs/cli/telemetry
Syncing CloudQuery providers [aws]

Initializing CloudQuery Providers...

✓ cq-provider-aws@v0.11.1 verified    1s  100 %

Finished provider initialization...

Checking available provider updates...

❌ failed to sync provider aws@latest.
Sync Diagnostics:

Type: Database Severity: Error
	Summary: dial tcp [::1]:5432: connect: connection refused

panic: value method github.com/cloudquery/cloudquery/pkg/core.FetchResponse.Properties called using nil *FetchResponse pointer [recovered]
	panic: value method github.com/cloudquery/cloudquery/pkg/core.FetchResponse.Properties called using nil *FetchResponse pointer

goroutine 1 [running]:
github.com/cloudquery/cloudquery/cmd.handleCommand.func1.2()
	/Users/yevgenyp/cloudquery/cmd/command.go:40 +0x68
panic({0x101fedc00, 0x14000884200})
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x204
github.com/cloudquery/cloudquery/pkg/core.(*FetchResponse).Properties(0x101fcff00?)
	<autogenerated>:1 +0x74
github.com/cloudquery/cloudquery/internal/analytics.Capture({0x101a4d0b8, 0x5}, {0x14000341710, 0x1, 0x1}, {0x102226d18, 0x0}, {0x14000884010?, 0x1, 0x1})
	/Users/yevgenyp/cloudquery/internal/analytics/client.go:163 +0x22c
github.com/cloudquery/cloudquery/cmd.glob..func3({0x1022387a8?, 0x1400028fe00?}, 0x140003329c0, 0x0?, {0x0?, 0x1?, 0x101aa0242?})
	/Users/yevgenyp/cloudquery/cmd/fetch.go:31 +0xf0
github.com/cloudquery/cloudquery/cmd.handleConsole({0x1022387e0, 0x1400019e008}, 0x14000696300?, {0x102dc4698, 0x0, 0x0}, 0x10221e050)
	/Users/yevgenyp/cloudquery/cmd/command.go:96 +0x304
github.com/cloudquery/cloudquery/cmd.handleCommand.func1(0x102d819a0, {0x102dc4698?, 0x0?, 0x0?})
	/Users/yevgenyp/cloudquery/cmd/command.go:43 +0x98
github.com/spf13/cobra.(*Command).execute(0x102d819a0, {0x102dc4698, 0x0, 0x0})
	/Users/yevgenyp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x102d81220)
	/Users/yevgenyp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yevgenyp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudquery/cloudquery/cmd.Execute()
	/Users/yevgenyp/cloudquery/cmd/root.go:96 +0x2c
main.main()
	/Users/yevgenyp/cloudquery/main.go:16 +0x6c
```

**Comment by roneli** [comment]
fixed in #615
