### ISSUE TITLE
bug(refactor): panic while  hitting ctrl+c

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#619]
### Describe the Bug

This bug relates only to the `dev` branch that will be merged soon. When running `cloudquery fetch` and then hitting `Ctrl+c` the following panic occures:

```
yevgenyp@yevgenys-mbp cloudquery % ./cloudquery fetch
Anonymous telemetry collection and crash reporting enabled. Run with --no-telemetry to disable, or check docs at https://docs.cloudquery.io/docs/cli/telemetry
Syncing CloudQuery providers [aws]

Initializing CloudQuery Providers...

✓ cq-provider-aws@v0.11.1 verified    0s  100 %

Finished provider initialization...

Checking available provider updates...

✓ sync provider aws to latest successfully.

Finished syncing providers...

Starting provider fetch...

⌛cq-provider-aws@latest fetching    3s [--------------------------------------------------------------|  Finished Resources: 1/152
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10369d9c8]

goroutine 112 [running]:
github.com/cloudquery/cloudquery/pkg/core.executeFetch({0x103f1c7a8, 0x1400029a440}, {{0x103f18a58, 0x14000292290}, 0xff, {0x0, 0x0}, {0x140004ace00, 0x1f, 0x1f4}, ...}, ...)
	/Users/yevgenyp/cloudquery/pkg/core/fetch.go:406 +0x8d8
github.com/cloudquery/cloudquery/pkg/core.runProviderFetch({0x103f1c7a8, 0x1400029a440}, 0x14000789e60, {{{0x140002b60b0, 0x3}, {0x140002b6aa8, 0x6}, {0x103738487, 0xa}}, 0x14000744200}, ...)
	/Users/yevgenyp/cloudquery/pkg/core/fetch.go:328 +0x7ac
github.com/cloudquery/cloudquery/pkg/core.Fetch.func1({{{0x140002b60b0, 0x3}, {0x140002b6aa8, 0x6}, {0x103738487, 0xa}}, 0x14000744200})
	/Users/yevgenyp/cloudquery/pkg/core/fetch.go:257 +0x108
created by github.com/cloudquery/cloudquery/pkg/core.Fetch
	/Users/yevgenyp/cloudquery/pkg/core/fetch.go:254 +0xe08
```

**Comment by roneli** [comment]
Fixed in #615
