### ISSUE TITLE
bug(github): Nil pointer dereference

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6667]
```
runtime error: invalid memory address or nil pointer dereference
goroutine 7860 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x64
github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveColumn.func1()
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.24.1/plugins/source/scheduler.go:93 +0x70
panic({0x100cd3b00, 0x1012633e0})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x20c
github.com/google/go-github/v48/github.(*RepositoryContent).GetContent(0x140003c6178?)
	/home/runner/go/pkg/mod/github.com/google/go-github/v48@v48.2.0/github/repos_contents.go:75 +0x18
github.com/cloudquery/cloudquery/plugins/source/github/resources/services/actions.resolveContents({0x100ddbda8, 0x14001795500}, {0x100dd5ee0?, 0x140003c8100}, 0x14000634e40, {{0x100b10f06, 0x8}, 0x5, {0x0, 0x0}, ...})
	/home/runner/work/cloudquery/cloudquery/plugins/source/github/resources/services/actions/workflows_fetch.go:67 +0x1a4
github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveColumn(0x1400029a0e0, {0x100ddbda8, 0x14001795500}, {{0x100dda2d8, 0x140002ba900}, 0x1, {0x0, 0x0}, {0x14000684a00, 0x45, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.24.1/plugins/source/scheduler.go:105 +0x134
github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResource(0x1400029a0e0, {0x100ddbde0, 0x140000912f0}, 0x140000d0a20, {0x100dd5ee0, 0x140003c8100}, 0x140015eab40?, {0x100d77b40, 0x1400089f3b0})
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.24.1/plugins/source/scheduler.go:69 +0x760
github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResourcesDfs.func1.1()
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.24.1/plugins/source/scheduler_dfs.go:157 +0xdc
created by github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResourcesDfs.func1
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.24.1/plugins/source/scheduler_dfs.go:153 +0xbc
```

**Comment by erezrokah** [comment]
Nice catch, we could skip the content in that case. I was actually wondering if we really need to get the content, but that's another issue
