### ISSUE TITLE
Bug(policy): Specifying a specific policy version from GitHub via `@` doesn't work

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#850]
### Describe the Bug
Running `cloudquery policy run 'github.com/cloudquery-policies/aws@v0.1.14'` fails to detect the policy from GitHub.

Running `cloudquery policy run 'github.com/cloudquery-policies/aws?ref=v0.1.14'` works.

### Expected Behavior

Per the docs, both variations should work https://docs.cloudquery.io/docs/cli/policy/overview

### CloudQuery Version

```sh
Version: 0.24.9
Commit: b5af06b570558612c95407dceb4200f92640f335
Date: 2022-06-06T13:32:45Z
```

### Debug Output

Console output:

```sh
failed to detect policy in hub: failed to detect url github.com/cloudquery-policies/aws@v0.1.14: failed to find latest version: failed to find policy aws@v0.1.14 latest versionDiagnostics:

Type: Resolving Severity: Error
	Summary: failed to detect policy in hub: failed to detect url github.com/cloudquery-policies/aws@v0.1.14: failed to find latest version: failed to find policy aws@v0.1.14 latest version
```

### Steps to Reproduce

```
cloudquery init aws
cloudquery fetch
cloudquery policy run 'github.com/cloudquery-policies/aws@v0.1.14'
```

**Comment by shimonp21** [comment]
Related: https://github.com/cloudquery/cloudquery/pull/841

**Comment by bbernays** [comment]
@shimonp21 - What am I missing... this issue seems to be about the go getter functionality specifically about the github source, while the issue linked seems to be about generic policies and how CQ executes them.

**Comment by shimonp21** [comment]
Hijacking this bug to report more issues when running policies:

- running a policy from a public github fails (works if no https):
   ```
    ~/projects/cqaws % ../cloudquery-shimonp21/cloudquery policy run https://github.com/shimonp21/shimon-example-cq-policy
    no valid policy with name "https://github.com/shimonp21/shimon-example-cq-policy" found. If using a local policy directory, ensure the path is correct and the directory existsDiagnostics:
    
    Type: User Severity: Error
            Summary: no valid policy with name "https://github.com/shimonp21/shimon-example-cq-policy" found. If using a local policy directory, ensure the path is correct and the directory exists
    
    policy has one or more errors, check logs
   ```

- Impossible to specify a local root policy with a "source" (not sure we actually want to fix this). If "./local-policy/policy.hcl":
  ```
  policy "aws" {
    source = "aws"
  }
  ```
  Then:
  ```
  ~/projects/cqaws % ../cloudquery-shimonp21/cloudquery policy run ./local-policy
    Starting policies run...

      ✓ policy "./local-policy" -  evaluating -       0s   Finished Checks: 1/1

      ❌ Failed to run policies

    Diagnostics:

    Type: User Severity: Error
        Summary: aws//: selected policy/query not found
        Detail: aws// not found, run `cloudquery policy describe aws` to find all available policies

   policy has one or more errors, check logs
  ``` 

- Panic when describing A local policy:
   ```
        ~/projects/cqaws % ../cloudquery-shimonp21/cloudquery policy describe ./shimon-policy-dir
    Describe Policy my-first-policy output:
    
    +-----------------+----------------------------+
    |      PATH       |        DESCRIPTION         |
    +-----------------+----------------------------+
    | my-first-policy | My First CloudQuery Policy |
    +-----------------+----------------------------+
    panic: runtime error: index out of range [0] with length 0 [recovered]
            panic: runtime error: index out of range [0] with length 0
    
    goroutine 1 [running]:
    github.com/cloudquery/cloudquery/cmd.handleCommand.func1.2()
            /Users/shimonp/projects/cloudquery-shimonp21/cmd/command.go:39 +0x5d
    panic({0x24d1180, 0xc0001e8858})
            /usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207
    github.com/cloudquery/cloudquery/pkg/ui/console.Client.describePolicy({{0x2996168, 0xc000818620}, 0xc00020a000, {0xc0004f1170, 0x1, 0x1}, {0x298f810, 0xc00081e680}, 0xc0008186e0, {0x298c7a0, ...}, ...}, ...)
            /Users/shimonp/projects/cloudquery-shimonp21/pkg/ui/console/client.go:649 +0x4dc
    github.com/cloudquery/cloudquery/pkg/ui/console.Client.DescribePolicies({{0x2996168, 0xc000818620}, 0xc00020a000, {0xc0004f1170, 0x1, 0x1}, {0x298f810, 0xc00081e680}, 0xc0008186e0, {0x298c7a0, ...}, ...}, ...)
            /Users/shimonp/projects/cloudquery-shimonp21/pkg/ui/console/client.go:473 +0x1f8
    github.com/cloudquery/cloudquery/cmd.glob..func6({0x2992d20?, 0xc000323200?}, 0x2992d20?, 0xc000323200?, {0xc0003a88e0?, 0x234d0a0?, 0x25f4c01?})
            /Users/shimonp/projects/cloudquery-shimonp21/cmd/policy.go:48 +0xa5
    github.com/cloudquery/cloudquery/cmd.handleConsole({0x2992d58, 0xc00019c000}, 0x1a?, {0xc0003a88e0, 0x1, 0x1}, 0x263bfe0)
            /Users/shimonp/projects/cloudquery-shimonp21/cmd/command.go:92 +0x2c3
    github.com/cloudquery/cloudquery/cmd.handleCommand.func1(0x3510d20, {0xc0003a88e0?, 0x1?, 0x1?})
            /Users/shimonp/projects/cloudquery-shimonp21/cmd/command.go:42 +0xb8
    github.com/spf13/cobra.(*Command).execute(0x3510d20, {0xc0003a88c0, 0x1, 0x1})
            /Users/shimonp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
    github.com/spf13/cobra.(*Command).ExecuteC(0x350fba0)
            /Users/shimonp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
    github.com/spf13/cobra.(*Command).Execute(...)
            /Users/shimonp/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
    github.com/cloudquery/cloudquery/cmd.Execute()
            /Users/shimonp/projects/cloudquery-shimonp21/cmd/root.go:95 +0x25
    main.main()
            /Users/shimonp/projects/cloudquery-shimonp21/main.go:8 +0x17
   ```

**Comment by erezrokah** [comment]
I believe this was fixed in https://github.com/cloudquery/cloudquery/pull/871

**Comment by yevgenypats** [comment]
This moved to `psql`. policy command was deprecated
